# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.39.2"

# base fastfile
import_from_git(url: 'ssh://git@stash.mgmt.local/mr/markit-fastlane.git', path: 'fastlane/Fastfile')

default_platform :ios

platform :ios do
  before_all do
      
    xcversion(
      version: "8.3.2"
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end
  after_all do |lane|
  end

  error do |lane, exception|
  end
end
